### ISSUE TITLE
Volume permission required to be set seperately from docker-compose file

### ISSUE THREAD

**Issue by casz** [vmware/vsphere-storage-for-docker#2089]
Initial volume does not give proper permission when used from docker-compose.

I have to manually create the volume and run `chown` on it.

```
docker volume create --name=jenkinsmaster_jenkins-home --driver=vsphere -o size=20gb
docker run -it -v jenkinsmaster_jenkins-home:/var/jenkins_home alpine chown -R 1000:1000 /var/jenkins_home
```

Docker-compose file
```
version: '3.6'

services:
  jenkins:
    restart: always
    build: .
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-home:/var/jenkins_home

volumes:
  jenkins-home:
    driver: vsphere:latest
    driver_opts:
      size: 20gb
```

Dockerfile
```
FROM jenkins/jenkins:lts-alpine

....
```
